apps/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('listar/', views.orders_list, name='orders_list'),
    path('editar/<int:id>', views.ord_edit, name='ord_edit'),
    path('exportar/', views.ord_export_op, name='ord_export_op'),
    path('enviar/esims/', views.send_esims, name='send_esims'),
    path('ativacoes/', views.orders_activations, name='orders_activations'),
    path('ativacoes/exportar', views.ord_export_act, name='ord_export_act'),
    
    # path('texto/', views.textImg, name='text_img'),
    # path('esimstore/', views.esimExpSis, name='esimstore'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.dashboard.views import index, clear_cache

urlpatterns = [
    path('', index, name='dashboard'),
    path('admin/', admin.site.urls),
    path('pedidos/', include('apps.orders.urls')),
    path('sims/', include('apps.sims.urls')),
    path('', include('apps.users.urls')),
    path('email/', include('apps.send_email.urls')),
    path('clear_cache/', clear_cache, name='clear_cache'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.sims.models import Sims

PRODUCT = [
    ('981', 'Norte Verizon'),
    ('980', 'Norte T-Mobile'),
    ('979', 'EUA Flex'),
    ('976', 'EUA Controle'),
    ('977', 'EUA Ilimitado'),
    ('975', 'Mundo'),
    ('974', 'Europa Flex'),
    ('971', 'Europa Controle'),
]

DATA = [
    ('500mb-dia', '500MB/Dia'),
    ('1gb-dia', '1GB / Dia'),
    ('2gb-dia', '2GB / Dia'),
    ('5gb-mes', '5GB / Mês'),
    ('10gb-mes', '10GB / Mês'),
    ('20gb-mes', '20GB / Mês'),
    ('30gb-mes', '30GB / Mês'),
    ('ilimitado', 'Ilimitado'),
]

ORDER_STATUS = [
    ('AA', 'Agd. Ativação'),
    ('AE', 'Agd. Envio'),
    ('AG', 'Agência'),
    ('AS', 'Atribuir SIM'),
    ('AI', 'Atribuir IMEI'),
    ('AT', 'Ativado'),
    ('CC', 'Cancelado'),
    ('CN', 'Concluido'),
    ('DE', 'Desativado'),
    ('DA', 'Data em Aberto'),
    ('EA', 'Erro Ativação'),
    ('ED', 'Erro Desativação'),
    ('EE', 'Enviar E-mail'),
    ('ES', 'Em Separação'),
    ('MB', 'Motoboy'),
    ('PC', 'Pag. Confirmado!'),
    ('PR', 'Processando'),
    ('RE', 'Reembolsar'),
    ('RB', 'Reembolsado'),
    ('RS', 'Reuso'),
    ('RP', 'Reprocessar'),
    ('RT', 'Retirada'),
    ('VS', 'Verificar SIM'),
]

SHIPMENTS = [
    ('FN', 'Frete Normal'),
    ('FE', 'Frete Expresso'),
    ('RT', 'Retirada'),
    ('MD', 'Mordomo'),
]

SHIP = [
    ('FN', 'Frete Normal'),
    ('FE', 'Frete Expresso'),
    ('RT', 'Retirada'),
    ('MD', 'Mordomo'),
]

class Orders(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default=0)
    item_id = models.CharField(max_length=15)
    client_id = models.IntegerField(null=True)  # Temporariamente permitindo nulo
    client = models.CharField(max_length=70)
    email = models.CharField(max_length=70, null=True, blank=True)
    product = models.CharField(max_length=50, choices=PRODUCT)
    data_day = models.CharField(max_length=30, choices=DATA)
    qty = models.IntegerField()
    coupon = models.CharField(max_length=25, default='')
    days = models.IntegerField()
    countries = models.BooleanField(default=False)
    cell_mod = models.CharField(max_length=45, null=True, blank=True)
    cell_imei = models.CharField(max_length=35, null=True, blank=True)
    cell_eid = models.CharField(max_length=35, null=True, blank=True)
    ord_chip_nun = models.CharField(max_length=35, null=True, blank=True)
    shipping = models.CharField(max_length=20, choices=SHIPMENTS, default='FN')
    ship = models.CharField(max_length=20, choices=SHIP, default='FN')
    order_date = models.DateTimeField()
    activation_date = models.DateField()
    order_status = models.CharField(max_length=20, choices=ORDER_STATUS, default='PR')
    type_sim = models.CharField(max_length=4, null=True, blank=True, default='sim')
    oper_sim = models.CharField(max_length=2, null=True, blank=True)
    id_sim = models.ForeignKey(Sims, on_delete=models.DO_NOTHING, null=True, blank=True)
    tracking = models.CharField(max_length=25, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        db_table = 'orders'
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering = ['order_id']

TYPE_NOTE = [
    ('S', 'Sistema'),
    ('P', 'Privada'),
]

class Notes(models.Model):
    id = models.AutoField(primary_key=True)
    id_item = models.ForeignKey(Orders, on_delete=models.DO_NOTHING, related_name='order_notes', default='')
    id_user = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='user_notes', default='', null=True, blank=True)
    note = models.TextField()
    type_note = models.CharField(max_length=1, choices=TYPE_NOTE, default='S')
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = 'notes'
        verbose_name = 'Nota'
        verbose_name_plural = 'Notas'
        ordering = ['-id']
    def __str__(self):
        return str(self.id_item)

apps/sims/models.py
from django.db import models

SIM_STATUS = [
    ('AT', 'Ativado'),
    ('CC', 'Cancelado'),    
    ('DS', 'Disponível'),
    ('DE', 'Desativado'),
    ('IN', 'Indisponível'),
    ('TC', 'Troca'),
]
SIM_OPERATOR = [
    ('TM', 'T-Mobile'), 
    ('CM', 'China Mobile'),
    ('TC', 'Telcom'),
    ('VR', 'Verizon'),
]
SIM_TYPES = [
    ('sim', 'SIM (Físico)'),   
    ('esim', 'eSIM (Virtual)'),
]

class Sims(models.Model):
    id = models.AutoField(primary_key=True, serialize=False)
    sim = models.CharField(max_length=25)
    link = models.URLField(null=True, blank=True, default='-')
    type_sim =  models.CharField(max_length=20, choices=SIM_TYPES, default='sim')
    operator = models.CharField(max_length=20, choices=SIM_OPERATOR)
    sim_status = models.CharField(max_length=20, choices=SIM_STATUS, default='DS')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        db_table = 'sims'
        verbose_name = 'Sim'
        verbose_name_plural = 'Sims'
        ordering = ['id']
    def __str__(self):
        return self.sim

apps/orders/views.py
from django.contrib.auth.models import User
from rolepermissions.decorators import has_permission_decorator
import csv
from django.http import HttpResponse
from datetime import date, datetime, timedelta
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.contrib import messages
from django.conf import settings
from apps.orders.models import Orders, Notes
from apps.sims.models import Sims
from apps.send_email.tasks import send_email_sims
from apps.sims.tasks import simDeactivateTC, simActivateTC
from .classes import ApiStore, StatusStore, DateFormats
from .tasks import order_import, orders_up_status
import pandas as pd


#Date today
today = datetime.now()

# Order list
@login_required(login_url='/login/')
@has_permission_decorator('view_orders')
def orders_list(request):
    global orders_l
    orders_l = ''

    url_cdn = settings.URL_CDN

    orders_all = Orders.objects.filter().order_by('-id')
    sims = Sims.objects.all().order_by('-id')
    orders_l = orders_all

    if request.method == 'GET':

        ord_name_f = request.GET.get('ord_name')
        ord_order_f = request.GET.get('ord_order')
        ord_sim_f = request.GET.get('ord_sim')
        oper_f = request.GET.get('oper')
        ord_st_f = request.GET.get('ord_st')

    if request.method == 'POST':

        ord_name_f = request.POST.get('ord_name_f')
        ord_order_f = request.POST.get('ord_order_f')  
        ord_sim_f = request.POST.get('ord_sim_f')
        oper_f = request.POST.get('oper_f')
        ord_st_f = request.POST.get('ord_st_f')

        if 'up_status' in request.POST:
            ord_id = request.POST.getlist('ord_id')
            ord_s = request.POST.get('ord_staus')
            id_user = request.user.id
            if ord_s != '':
                orders_up_status.delay(ord_id, ord_s,id_user)                               

     # FIlters

    url_filter = ''

    if ord_name_f:
        orders_l = orders_l.filter(client__icontains=ord_name_f)
        url_filter += f"&ord_name={ord_name_f}"

    if ord_order_f: 
        orders_l = orders_l.filter(item_id__icontains=ord_order_f)   
        url_filter += f"&ord_order={ord_order_f}"

    if ord_sim_f: 
        orders_l = orders_l.filter(id_sim__sim__icontains=ord_sim_f)
        url_filter += f"&ord_sim={ord_sim_f}"

    if oper_f: 
        orders_l = orders_l.filter(id_sim__operator__icontains=oper_f)
        url_filter += f"&oper={oper_f}"

    if ord_st_f: 
        orders_l = orders_l.filter(order_status__icontains=ord_st_f)
        url_filter += f"&ord_st={ord_st_f}"

    ord_status = Orders.order_status.field.choices
    oper_list = Sims.operator.field.choices

    # Listar status dos pedidos
    ord_st_list = []
    for ord_s in ord_status:
        ord = orders_all.filter(order_status=ord_s[0]).count()
        ord_st_list.append((ord_s[0],ord_s[1],ord))

    # Paginação
    paginator = Paginator(orders_l, 50)
    page = request.GET.get('page')
    orders = paginator.get_page(page)

    from rolepermissions.permissions import available_perm_status

    context = {
        'url_cdn': url_cdn,
        'orders_l': orders_l,
        'orders': orders,
        'sims': sims,
        'ord_st_list': ord_st_list,
        'oper_list': oper_list,
        'url_filter': url_filter,
    }
    return render(request, 'painel/orders/index.html', context)


# Order Edit
@login_required(login_url='/login/')
@has_permission_decorator('edit_orders')
def ord_edit(request,id):
    if request.method == 'GET':
            
        order = Orders.objects.get(pk=id)
        ord_status = Orders.order_status.field.choices
        ord_product = Orders.product.field.choices
        ord_data_day = Orders.data_day.field.choices
        
        context = {
            'order': order,
            'ord_status': ord_status,
            'ord_product': ord_product,
            'ord_data_day': ord_data_day,
            'days': range(1, 31),
        }
        return render(request, 'painel/orders/edit.html', context)
        
    if request.method == 'POST':
        
        print('>>>>>>>>>> EDITAR PEDIDO')
        
        global msg_info
        msg_info = []
        global msg_error
        msg_error = []
        global id_sim
        id_sim = ''
        global ord_st
        ord_st = ''
        global update_store
        update_store = {}
        
        order = Orders.objects.get(pk=id)
        order_id = order.order_id
        try: order_sim = order.id_sim.sim
        except: order_sim = ''
        try: sim_id = int(order.id_sim.id)
        except: sim_id = ''
        days = request.POST.get('days')
        product = request.POST.get('product')
        data_day = request.POST.get('data_day')
        type_sim = request.POST.get('type_sim')
        operator = request.POST.get('operator')
        sim = request.POST.get('sim')
        activation_date = request.POST.get('activation_date')
        email = request.POST.get('email')
        cell_imei = request.POST.get('cell_imei')
        cell_eid = request.POST.get('cell_eid')
        tracking = request.POST.get('tracking')
        ord_st = request.POST.get('ord_st_f')
        ord_note = request.POST.get('ord_note')
        up_oper = request.POST.get('upOper')
        esim_v = None
                
        # Update SIM in Order and update SIM
        def updateSIM():
            # Update SIM
            sim_put = Sims.objects.get(pk=sim_id)            
            sim_put.sim_status = 'TC'
            sim_put.save()
            # Delete SIM in Order
            order_put = Orders.objects.get(pk=order.id)
            order_put.id_sim_id = ''
            order_put.save()
        
        # Insert SIM in Order
        def insertSIM(ord_st=None):
            sim_up = Sims.objects.filter(sim_status='DS', type_sim=type_sim, operator=operator).first()
            if sim_up:
                sim_put = Sims.objects.get(pk=sim_up.id)
                if order_sim != '':
                    # Update SIM
                    updateSIM()
                sim_put.sim_status = 'AT'
                sim_put.save()
                
                if type_sim == 'esim': 
                    ord_st = 'EE'
                else: ord_st = ord_st
                
                order_put = Orders.objects.get(pk=order.id)
                order_put.id_sim_id = sim_put.id
                order_put.order_status = ord_st
                order_put.save()
            else:       
                msg_error.append(f'Não há estoque de {operator} - {type_sim} no sistema')
                        
        # Liberar SIMs
        if ord_st == 'CC' or ord_st == 'DE' or ord_st == 'RE':
            print('>>>>>>>>>> Liberar SIMs')
            if order_sim != '':
                # Change TC
                if order.id_sim.operator == 'TC':
                    simDeactivateTC(id=order.id)
                
                # Update SIM
                sim_put = Sims.objects.get(pk=sim_id)
                sim_put.sim_status = 'DE'
                sim_put.save()    

        # Activate TC
        if ord_st == 'AT' and order.order_status != 'AT' and operator == 'TC':
            simActivateTC(id=order.id)

        # Se SIM preenchico
        if sim:
            # Verificar se Operadora e Tipo de SIM estão marcados
            if operator != None and type_sim != None:
                if order_sim != '':
                    # Alterar status no sistema e no site
                    updateSIM()
                
                sims_all = Sims.objects.all().filter(sim=sim)
                if sims_all:
                        messages.info(request,f'O SIM {sim} já está cadastrado no sistema')
                else:
                    # Save SIMs - Insert Stock
                    add_sim = Sims( 
                        sim = sim,
                        type_sim = type_sim,
                        operator = operator,
                        sim_status = 'AT',
                    )
                    add_sim.save()
                
                    # Update order
                    order_put = order
                    order_put.id_sim_id = add_sim.id
                    order_put.save()
                    up_plan = True # verificação para nota
            else:
                msg_error.append(f'Você precisa selecionar o tipo de SIM e a Operadora')
        else:
            # Troca de SIM
            if order_sim != '':
                if order.id_sim.operator != operator or order.id_sim.type_sim != type_sim or up_oper != None:
                    updateSIM()
                    insertSIM(ord_st)
                    up_plan = True # verificação para nota
                    
                    # Update SIM
                    esim_v = True             
            else:
                if operator != None and type_sim != None:
                    if product != '974' and type_sim != 'esim':
                        insertSIM(ord_st)
                        up_plan = True # verificação para nota
            
        # Update Order
        if activation_date == '':
            activation_date = order.activation_date
        if email == '':
            email = order.email
                
        order_put = Orders.objects.get(pk=order.id)
        order_put.days = days
        order_put.product = product
        order_put.data_day = data_day
        order_put.activation_date = activation_date
        order_put.email = email
        order_put.cell_imei = cell_imei
        order_put.cell_eid = cell_eid
        order_put.tracking = tracking
        order_put.order_status = ord_st
        order_put.save()
        
        # Notes

templates/painel/orders/export_op.html
{% extends 'painel/partials/_content_default.html' %}
{% load static %}
{% block title_page %}<i class="bi bi-shop" style="font-size: 1.2em;"></i> Pedidos{% endblock %}
{% block title_content %}Exportar Pedidos{% endblock %}

{% block content_def %}
    <form class="row g-3" action="{% url 'ord_export_op' %}" method="POST">
        {% csrf_token %}
        <div class="d-flex flex-column flex-sm-row">
            <div class="dm-select-list me-3">
                <div class="dm-select ">
                    <select name="ord_op_f" id="ord_op_f" class="form-control form-control-lg ps-3 pe-5">
                        <option value="op_all">Todas as Operadoras</option>
                        {% for sims_o in sims_op %}
                        <option value="{{sims_o.0}}">{{sims_o.1}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="dm-select-list">
                <button type="submit" class="btn btn-default btn-rounded color-primary btn-primary">
                    <span class="flex items-center">
                        <i class="bi bi-download"></i> <span>Exportar para Ativação</span>
                    </span>
                </button>
            </div>
        </div>
        <div class="form-text ms-3"><br>OBS: Para exportação os pedidos precisam estar com o status <b>Agd. Ativação</b>.</div>
    </form>

{% endblock %}

templates/painel/orders/index.html
{% extends 'painel/partials/_content_default.html' %}
{% load static %}
{% load permission_tags %}
{% load date_day %}
{% load status_count %}
{% block title_page %}<i class="bi bi-shop"></i> Pedidos{% endblock %}
{% block title_content %}Todos os Pedidos{% endblock %}

{% block css_custom %}
<style>
    .custom-tooltip {
        --bs-tooltip-bg: var(--bs-secondary);
        --bs-popover-body-padding-x: 0.1rem;
        --bs-popover-body-padding-y: 0.1rem;
    }

    .custom-popover {
        --bs-popover-border-color: var(--bs-secondary);
        --bs-popover-body-padding-x: 1rem;
        --bs-popover-body-padding-y: .5rem;
    }
</style>
{% endblock %}

{% block js_custom %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
{% endblock %}

{% block content_def %}

{% if request.user|can:'edit_sims' %}
<div class="col-md-12">

    <div class="dm-button-list d-flex flex-wrap">
        {% for ord_sts in ord_st_list %}
        {% if ord_sts.2 != 0 %}
        <button class="btn btn-default btn-squared color-primary btn-outline-primary m-1">{{ord_sts.1}}
            ({{ord_sts.2}})</button>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endif %}
<form class="row g-3" action="{% url 'orders_list' %}" method="POST">
    {% csrf_token %}
    {% if request.user|can:'edit_orders' %}
    <div class="col-md-1">
        <div class="dm-select">
            <select class="form-control form-control-lg ps-3 pe-5" name="ord_staus">
                <option value="" selected>Alterar Status</option>
                {% for ord_st in ord_st_list %}
                <option value="{{ord_st.0}}">{{ord_st.1}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md-1">
        <button type="submit" class="btn btn-default btn-rounded color-primary btn-primary"
            name="up_status">Alterar</button>
    </div>
    {% endif %}
    <div class="col-md-2">
        <input type="text" class="form-control form-control-lg" placeholder="Nome" name="ord_name_f">
    </div>
    <div class="col-md-1">
        <input type="text" class="form-control form-control-lg" placeholder="Pedido" name="ord_order_f">
    </div>
    <div class="col-md-1">
        <input type="text" class="form-control form-control-lg" placeholder="(e)SIM)" name="ord_sim_f">
    </div>
    <div class="col-md-2">
        <div class="dm-select">
            <select class="form-control form-control-lg ps-3 pe-5" name="oper_f">
                <option value="" selected>Todas Operadoras</option>
                {% for op_s in oper_list %}
                <option value="{{op_s.0}}">{{op_s.1}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md-2">
        <div class="dm-select">
            <select class="form-control form-control-lg ps-3 pe-5" name="ord_st_f">
                <option value="" selected>Todos Status</option>
                {% for ord_st in ord_st_list %}
                {% if ord_st.2 != 0 %}
                <option value="{{ord_st.0}}">{{ord_st.1}} ({{ord_st.2}})</option>
                {% endif %}
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md-1">
        <button type="submit" class="btn btn-default btn-rounded color-primary btn-primary"
            name="up_filter">Filtrar</button>
    </div>
    <div class="col-md-1 p-2">
        <div class="application-task d-flex align-items-center">
            <a class="btn-default btn-rounded" href="{% url 'orders_list' %}">
                <i class="bi bi-arrow-clockwise"></i>Limpar
            </a>
        </div>

    </div>
    <div class="table-responsive">
        <table class="table mb-0 table-hover table-responsive">
            <thead>
                <tr class="userDatatable-header">
                    <th><input class="form-check-input" type="checkbox" id="checkAll"></th>
                    <th class="userDatatable-title">Pedido</th>
                    <th class="userDatatable-title">Cliente</th>
                    <th class="userDatatable-title">(e)SIM</th>
                    <th class="userDatatable-title">Op.</th>
                    <th class="userDatatable-title">Produto</th>
                    <th class="userDatatable-title text-center">Países</th>
                    <th class="userDatatable-title text-center">Dias</th>
                    <th class="userDatatable-title">Celular</th>
                    <th class="userDatatable-title">Ped./Chip</th>
                    <th class="userDatatable-title text-center">Ativação</th>
                    <th class="userDatatable-title text-center">Término</th>
                    <th class="userDatatable-title text-center">Status</th>
                    <th class="userDatatable-title">
                        {% if request.user|can:'edit_orders' %}Ações{% endif %}
                    </th>
                </tr>
            </thead>
            <tbody>
                {% if orders %}
                {% for order in orders %}
                <tr class="table-tr">
                    <td class="text-center">
                        <div class="userDatatable-content">
                            <input class="checkItem form-check-input " type="checkbox" value="{{order.id}}"
                                name="ord_id">
                        </div>
                    </td>
                    <td>
                        <div class="userDatatable-content">{{ order.item_id }}</div>
                    </td>
                    <td>
                        <div class="userDatatable-content">{{ order.client|truncatechars:25 }}</div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">
                            {% if order.id_sim %}
                            <span data-bs-toggle="popover" data-bs-placement="top" data-bs-custom-class="custom-popover"
                                data-bs-content="{{order.id_sim.get_operator_display}} - {% if order.id_sim.type_sim == 'sim' %}SIM{% elif order.id_sim.type_sim == 'esim' %}eSIM{% endif %}">
                                {{ order.id_sim }}
                            </span>
                            {% else %}
                            -
                            {% endif %}

                            {% if order.id_sim.type_sim == 'esim' %} 
                                <a href="{{ url_cdn }}{{ order.id_sim.link }}" target="_blank">
                                    <i class="bi bi-qr-code text-primary ps-2" data-bs-toggle="tooltip"
                                        data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                                        data-bs-title="Ver QRCode">
                                    </i>
                                </a>
                            {% endif %}
                        </div>
                    </td>
                    <td>
                        <div class="userDatatable-content">{{ order.id_sim.operator }}</div>
                    </td>
                    <td>
                        <div class="userDatatable-content">
                            {{ order.get_product_display }} {{ order.get_data_day_display }}
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="userDatatable-content">
                            {% if order.countries == 0 %}-{% else %}
                            <span class="badge badge-round badge-lg alert-success">Sim</span>
                            {% endif %}
                        </div>
                    </td>
                    <td>
                        <div class="userDatatable-content">{{ order.days }}</div>
                    </td>
                    <td>
                        <div class="userDatatable-content">
                            {% if order.cell_mod %}
                                <i class="bi bi-phone text-primary"
                                    style="cursor: pointer;"
                                    data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top"
                                    data-bs-content="{{order.cell_mod}}">
                                </i>
                            {% endif %}
                            {% if order.cell_imei %}
                                <i class="bi bi-phone text-secondary"
                                    style="cursor: pointer;" 
                                    data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top"
                                    data-bs-content="IMEI - {{order.cell_imei}}">
                                </i>
                            {% endif %}
                            {% if order.cell_eid %}
                                <i class="bi bi-phone text-secondary" 
                                    style="cursor: pointer;" 
                                    data-bs-container="body" data-bs-toggle="popover" data-bs-placement="top"
                                    data-bs-content="EID - {{order.cell_eid}}">
                                </i>
                            {% endif %}
                        </div>
                    </td>
                    <td>
                        <div class="userDatatable-content">{{ order.ord_chip_nun }}</div>
                    </td>
                    <td class="text-center">
                        <div class="userDatatable-content">{{ order.activation_date|date:"d/m/Y" }}</div>
                    </td>
                    <td class="text-center">
                        <div class="userDatatable-content">
                            {% with a=order.activation_date b=order.days %}
                            {% dateaddday a b %}
                            {% endwith %}
                        </div>
                    </td>
                    <td class="text-center">
                        <div class="userDatatable-content">{{ order.get_order_status_display }}</div>
                    </td>
                    <td>
                        <div class="userDatatable-content">
                            {% if request.user|can:'edit_orders' %}
                            <a href="{% url 'ord_edit' order.id %}">
                                <i class="bi bi-pencil-square pe-1 text-info" data-bs-toggle="tooltip"
                                    data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                                    data-bs-title="Editar"></i></a>
                            {% if order.id_sim != None %}
                            <a href="{% url 'send_email' order.id %}">
                                <i class="bi bi-envelope-at pe-1 text-primary" data-bs-toggle="tooltip"
                                    data-bs-placement="top" data-bs-custom-class="custom-tooltip"
                                    data-bs-title="Enviar e-mail"></i></a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr class="table-tr">
                    <td>
                        <div class="userDatatable-content">
                            Nenhum pedido encontrado.
                        </div>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    <nav aria-label="navigation">
        <ul class="pagination">
            {% if orders.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ orders.previous_page_number }}{{ url_filter }}"
                    aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="">
                    {{ orders.number }} de {{ orders.paginator.num_pages }}</a>
            </li>
            {% if orders.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ orders.next_page_number }}{{ url_filter }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
</form>

{% endblock %}
{% block script_custom %}
<script>
    $(document).ready(function () {
        // Ação do botão "Marcar Todos"
        $('#checkAll').on('change', function () {
            $('.checkItem').prop('checked', this.checked);
        });
    });
</script>
<script>
    /* Tooltips */
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    /* Popovers */
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
</script>
{% endblock %}