apps/sims/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('listar/', views.sims_list, name='sims_index'),
    path('adicionar/sim/', views.sims_add_sim, name='sims_add_sim'),
    path('adicionar/esim/', views.sims_add_esim, name='sims_add_esim'),
    path('sims/pedidos', views.sims_ord, name='sims_ord'),
    path('estoque/exportar', views.exportSIMs, name='exportSIMs'),
    path('delsim', views.delSIMs, name='delsim'),
    path('delsimtc', views.delSimTC, name='delsimtc'),
    # path('verificar', views.verify_sim, name='verify_sim'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from apps.dashboard.views import index, clear_cache

urlpatterns = [
    path('', index, name='dashboard'),
    path('admin/', admin.site.urls),
    path('pedidos/', include('apps.orders.urls')),
    path('sims/', include('apps.sims.urls')),
    path('', include('apps.users.urls')),
    path('email/', include('apps.send_email.urls')),
    path('clear_cache/', clear_cache, name='clear_cache'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.sims.models import Sims

PRODUCT = [
    ('981', 'Norte Verizon'),
    ('980', 'Norte T-Mobile'),
    ('979', 'EUA Flex'),
    ('976', 'EUA Controle'),
    ('977', 'EUA Ilimitado'),
    ('975', 'Mundo'),
    ('974', 'Europa Flex'),
    ('971', 'Europa Controle'),
]

DATA = [
    ('500mb-dia', '500MB/Dia'),
    ('1gb-dia', '1GB / Dia'),
    ('2gb-dia', '2GB / Dia'),
    ('5gb-mes', '5GB / Mês'),
    ('10gb-mes', '10GB / Mês'),
    ('20gb-mes', '20GB / Mês'),
    ('30gb-mes', '30GB / Mês'),
    ('ilimitado', 'Ilimitado'),
]

ORDER_STATUS = [
    ('AA', 'Agd. Ativação'),
    ('AE', 'Agd. Envio'),
    ('AG', 'Agência'),
    ('AS', 'Atribuir SIM'),
    ('AI', 'Atribuir IMEI'),
    ('AT', 'Ativado'),
    ('CC', 'Cancelado'),
    ('CN', 'Concluido'),
    ('DE', 'Desativado'),
    ('DA', 'Data em Aberto'),
    ('EA', 'Erro Ativação'),
    ('ED', 'Erro Desativação'),
    ('EE', 'Enviar E-mail'),
    ('ES', 'Em Separação'),
    ('MB', 'Motoboy'),
    ('PC', 'Pag. Confirmado!'),
    ('PR', 'Processando'),
    ('RE', 'Reembolsar'),
    ('RB', 'Reembolsado'),
    ('RS', 'Reuso'),
    ('RP', 'Reprocessar'),
    ('RT', 'Retirada'),
    ('VS', 'Verificar SIM'),
]

SHIPMENTS = [
    ('FN', 'Frete Normal'),
    ('FE', 'Frete Expresso'),
    ('RT', 'Retirada'),
    ('MD', 'Mordomo'),
]

SHIP = [
    ('FN', 'Frete Normal'),
    ('FE', 'Frete Expresso'),
    ('RT', 'Retirada'),
    ('MD', 'Mordomo'),
]

class Orders(models.Model):
    id = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default=0)
    item_id = models.CharField(max_length=15)
    client_id = models.IntegerField(null=True)  # Temporariamente permitindo nulo
    client = models.CharField(max_length=70)
    email = models.CharField(max_length=70, null=True, blank=True)
    product = models.CharField(max_length=50, choices=PRODUCT)
    data_day = models.CharField(max_length=30, choices=DATA)
    qty = models.IntegerField()
    coupon = models.CharField(max_length=25, default='')
    days = models.IntegerField()
    countries = models.BooleanField(default=False)
    cell_mod = models.CharField(max_length=45, null=True, blank=True)
    cell_imei = models.CharField(max_length=35, null=True, blank=True)
    cell_eid = models.CharField(max_length=35, null=True, blank=True)
    ord_chip_nun = models.CharField(max_length=35, null=True, blank=True)
    shipping = models.CharField(max_length=20, choices=SHIPMENTS, default='FN')
    ship = models.CharField(max_length=20, choices=SHIP, default='FN')
    order_date = models.DateTimeField()
    activation_date = models.DateField()
    order_status = models.CharField(max_length=20, choices=ORDER_STATUS, default='PR')
    type_sim = models.CharField(max_length=4, null=True, blank=True, default='sim')
    oper_sim = models.CharField(max_length=2, null=True, blank=True)
    id_sim = models.ForeignKey(Sims, on_delete=models.DO_NOTHING, null=True, blank=True)
    tracking = models.CharField(max_length=25, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        db_table = 'orders'
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'
        ordering = ['order_id']

TYPE_NOTE = [
    ('S', 'Sistema'),
    ('P', 'Privada'),
]

class Notes(models.Model):
    id = models.AutoField(primary_key=True)
    id_item = models.ForeignKey(Orders, on_delete=models.DO_NOTHING, related_name='order_notes', default='')
    id_user = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name='user_notes', default='', null=True, blank=True)
    note = models.TextField()
    type_note = models.CharField(max_length=1, choices=TYPE_NOTE, default='S')
    created_at = models.DateTimeField(auto_now_add=True)
    class Meta:
        db_table = 'notes'
        verbose_name = 'Nota'
        verbose_name_plural = 'Notas'
        ordering = ['-id']
    def __str__(self):
        return str(self.id_item)

apps/sims/models.py
from django.db import models

SIM_STATUS = [
    ('AT', 'Ativado'),
    ('CC', 'Cancelado'),    
    ('DS', 'Disponível'),
    ('DE', 'Desativado'),
    ('IN', 'Indisponível'),
    ('TC', 'Troca'),
]
SIM_OPERATOR = [
    ('TM', 'T-Mobile'), 
    ('CM', 'China Mobile'),
    ('TC', 'Telcom'),
    ('VR', 'Verizon'),
]
SIM_TYPES = [
    ('sim', 'SIM (Físico)'),   
    ('esim', 'eSIM (Virtual)'),
]

class Sims(models.Model):
    id = models.AutoField(primary_key=True, serialize=False)
    sim = models.CharField(max_length=25)
    link = models.URLField(null=True, blank=True, default='-')
    type_sim =  models.CharField(max_length=20, choices=SIM_TYPES, default='sim')
    operator = models.CharField(max_length=20, choices=SIM_OPERATOR)
    sim_status = models.CharField(max_length=20, choices=SIM_STATUS, default='DS')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        db_table = 'sims'
        verbose_name = 'Sim'
        verbose_name_plural = 'Sims'
        ordering = ['id']
    def __str__(self):
        return self.sim

apps/sims/forms.py
from django import forms
from apps.sims.models import Sims

class AddSims(forms.Form):
        class Meta:
            model = Sims
            fields = ['__all__']

apps/sims/views.py
from django.contrib.auth.decorators import login_required
from rolepermissions.decorators import has_permission_decorator
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse
from datetime import date
from django.core.paginator import Paginator
from django.contrib import messages
from django.conf import settings
from django.core.files.storage import default_storage
import csv
import imghdr
import boto3

from apps.sims.models import Sims
from apps.orders.models import Orders
from apps.orders.classes import ApiStore
from .tasks import sims_in_orders


# Script Upload S3
def get_s3_client():
    return boto3.client(
        's3', 
        aws_access_key_id=settings.AWS_ACCESS_KEY_ID, 
        aws_secret_access_key=settings.AWS_SECRET_ACCESS_KEY
    )

def upload_file_to_s3(file):
    s3 = get_s3_client()
    bucket_name = settings.AWS_STORAGE_BUCKET_NAME
    file_path = f"{settings.MEDIA_LOCATION}/{file.name}"
    s3.upload_fileobj(file, bucket_name, file_path)
    return default_storage.url(file_path)

@login_required(login_url='/login/')
@has_permission_decorator('view_sims')
def sims_list(request):
    global sims_l
    sims_l = ''
    
    sims_all = Sims.objects.all().order_by('-id')
    sims_l = sims_all
    url_cdn = settings.URL_CDN
    
    if request.method == 'GET':
        
        sim_f = request.GET.get('sim')
        sim_type_f = request.GET.get('sim_type')    
        sim_status_f = request.GET.get('sim_status')
        sim_oper_f = request.GET.get('sim_oper')
    
    if request.method == 'POST':
        
        sim_f = request.POST.get('sim_f')
        sim_type_f = request.POST.get('sim_type_f')       
        sim_status_f = request.POST.get('sim_status_f')
        sim_oper_f = request.POST.get('sim_oper_f')
            
        if 'up_status' in request.POST:
                sim_id = request.POST.getlist('sim_id')
                sim_st = request.POST.get('sim_st')
                if sim_id and sim_st:
                    for o_id in sim_id:
                        sim = Sims.objects.get(pk=o_id)
                        sim.sim_status = sim_st
                        sim.save()
                        
                    messages.success(request,f'SIM(s) atualizado(s) com sucesso!')
                else:
                    messages.info(request,f'Você precisa marcar alguma opção')
    
    # FIlters
    
    url_filter = ''
    
    if sim_f:
        sims_l = sims_l.filter(sim__icontains=sim_f)
        url_filter += f"&sim={sim_f}"

    if sim_type_f: 
        sims_l = sims_l.filter(type_sim__icontains=sim_type_f)        
        url_filter += f"&sim_type={sim_type_f}"
    
    if sim_status_f: 
        sims_l = sims_l.filter(sim_status__icontains=sim_status_f)
        url_filter += f"&sim_status={sim_status_f}"
    
    if sim_oper_f: 
        sims_l = sims_l.filter(operator__icontains=sim_oper_f)
        url_filter += f"&sim_oper={sim_oper_f}"
        
    
    sims_types = Sims.type_sim.field.choices
    sims_status = Sims.sim_status.field.choices
    sims_oper = Sims.operator.field.choices
    
    paginator = Paginator(sims_l, 50)
    page = request.GET.get('page')
    sims = paginator.get_page(page)
    
    # Verificar estoque de operadoras
    sim_tm = sims_all.filter(sim_status='DS',operator='TM', type_sim='sim').count()
    esim_tm = sims_all.filter(sim_status='DS',operator='TM', type_sim='esim').count()
    sim_cm = sims_all.filter(sim_status='DS',operator='CM', type_sim='sim').count()
    esim_cm = sims_all.filter(sim_status='DS',operator='CM', type_sim='esim').count()
    sim_tc = sims_all.filter(sim_status='DS',operator='TC', type_sim='sim').count()
    esim_tc = sims_all.filter(sim_status='DS',operator='TC', type_sim='esim').count()
    
    url = reverse('sims_index')
    
    context= {
        'url': url,
        'url_cdn': url_cdn,
        'sims': sims,
        'sims_types': sims_types,
        'sims_status': sims_status,
        'sims_oper': sims_oper,
        'sim_tm': sim_tm,
        'esim_tm': esim_tm,
        'sim_cm': sim_cm,
        'esim_cm': esim_cm,
        'sim_tc': sim_tc,
        'esim_tc': esim_tc,
        'url_filter': url_filter,
    }
       
    return render(request, 'painel/sims/index.html', context)

@login_required(login_url='/login/')
@has_permission_decorator('add_sims')
def sims_add_sim(request):
    
    from rolepermissions.permissions import available_perm_status
    
    global orders_l
    orders_l = ''

    orders_all = Orders.objects.all().order_by('-id').filter(order_status='AS').filter(id_sim=None)
    orders_l = orders_all
    
    if request.method == 'GET':

        ord_name_f = request.GET.get('ord_name')
        ord_order_f = request.GET.get('ord_order')
        ord_sim_f = request.GET.get('ord_sim')
        oper_f = request.GET.get('oper')
        ord_st_f = request.GET.get('ord_st')

    if request.method == 'POST':

        ord_name_f = request.POST.get('ord_name_f')
        ord_order_f = request.POST.get('ord_order_f')  
        ord_sim_f = request.POST.get('ord_sim_f')
        oper_f = request.POST.get('oper_f')
        ord_st_f = request.POST.get('ord_st_f')
        
        # Salvar Pedido com SIM
        if 'save_sims' in request.POST:
            order_ids = request.POST.getlist('ord_id')
            for order_id in order_ids:
                ord_id = int(order_id)
                order = Orders.objects.get(id=ord_id)
                item_id = order.order_id
                ord_oper = request.POST.get(f'ord_oper_{ord_id}')
                ord_sim = request.POST.get(f'ord_sim_{ord_id}')
                
                print(f'item_id >>>>>>>>> {item_id}')
                
                if ord_sim != '':
                    # Salvar SIM
                    add_sim = Sims(
                        sim = ord_sim,
                        type_sim = 'sim',
                        operator = ord_oper,
                        sim_status = 'AT'
                    )
                    add_sim.save()
                    sim_id = add_sim.id
                    # Salvar Pedido
                    order.id_sim = add_sim
                    order.order_status = 'AE'                
                    order.save()
                    #ALterar status no site
                    try:
                        apiStore = ApiStore.conectApiStore()
                        update_store = {
                                'status': 'agd-envio'
                            }
                        apiStore.put(f'orders/{item_id}', update_store).json()
                        
                        apiStore = ApiStore.conectApiStore()
                        update_store = {
                                'status': 'agd-envio'
                            }
                        apiStore.put(f'orders/{order_id}', update_store).json()
                                        
                    except Exception as e:
                        messages.error(request,f'Erro ao atualizar status do pedido {order} no site: {e}')
                    
            messages.success(request,f'SIM(s) atualizado(s) com sucesso!')        
    
    url_filter = ''

    if ord_name_f:
        orders_l = orders_l.filter(client__icontains=ord_name_f)
        url_filter += f"&ord_name={ord_name_f}"

    if ord_order_f: 
        orders_l = orders_l.filter(item_id__icontains=ord_order_f)   
        url_filter += f"&ord_order={ord_order_f}"

    if ord_sim_f: 
        orders_l = orders_l.filter(id_sim__sim__icontains=ord_sim_f)
        url_filter += f"&ord_sim={ord_sim_f}"

    if oper_f: 
        orders_l = orders_l.filter(id_sim__operator__icontains=oper_f)
        url_filter += f"&oper={oper_f}"

    if ord_st_f: 
        orders_l = orders_l.filter(order_status__icontains=ord_st_f)
        url_filter += f"&ord_st={ord_st_f}"

    ord_status = Orders.order_status.field.choices
    oper_list = Sims.operator.field.choices
    shipp_list = Orders.shipping.field.choices
    
    # Listar status dos pedidos
    ord_st_list = []
    for ord_s in ord_status:
        ord = orders_all.filter(order_status=ord_s[0]).count()
        ord_st_list.append((ord_s[0],ord_s[1],ord))
    
    # Paginação
    paginator = Paginator(orders_l, 50)
    page = request.GET.get('page')
    orders = paginator.get_page(page)
    
    print(f'orders >>>>>>>>> {orders}')
    print(f'orders_l >>>>>>>>> {orders_l}')

    context = {
        'orders_l': orders_l,
        'orders': orders,
        'oper': '',
        'ord_st_list': ord_st_list,
        'oper_list': oper_list,
        'shipp_list': shipp_list,
        'url_filter': url_filter,
    }
    return render(request, 'painel/sims/add-sim.html', context)

@login_required(login_url='/login/')
@has_permission_decorator('edit_sims')
def sims_add_esim(request):
    if request.method == "GET":
        
        operator_list = Sims.operator.field.choices
        
        context = {
            'operator_list': operator_list,
        }
        
        return render(request, 'painel/sims/add-esim.html', context)
    
    if request.method == 'POST':
                
        type_sim = request.POST.get('type_sim')
        operator = request.POST.get('operator')
        esims = request.FILES.getlist('esim')
 
        if type_sim == '' or operator == '' or esims == '':
            messages.error(request,'Preencha todos os campos')
            return render(request, 'painel/sims/add-esim.html')
                           
        
        for sim_img in esims:
            sim_i = sim_img.name.split('.')
            
            print(sim_img.name)
            print(sim_img)
            
            fileurl = ''

templates/painel/sims/add-sim.html
{% extends 'painel/partials/_content_default.html' %}
{% load static %}
{% load date_day %}
{% block title_page %}<i class="bi bi-sim" style="font-size: 1.2em;"></i> SIMs{% endblock %}
{% block title_content %}Adicionar SIMs{% endblock %}

{% block content_def %}

{% comment %} {% if request.user|can:'edit_sims' %} {% endcomment %}
<div class="col-md-12">

    <div class="dm-button-list d-flex flex-wrap">
        {% for ord_sts in ord_st_list %}
        {% if ord_sts.2 != 0 %}
        <button class="btn btn-default btn-squared color-primary btn-outline-primary m-1">{{ord_sts.1}}
            ({{ord_sts.2}})</button>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% comment %} {% endif %} {% endcomment %}
<div class="col-md-12 py-3">
<form class="row g-3" action="{% url 'orders_list' %}" method="POST">
    {% csrf_token %}
    <div class="col-md-2">
        <div id="pageContentArea" class="pageSection">
            <input type="text" id="activReturn_f" name="activReturn_f"
                class="inputField shortInputField dateRangeField form-control  ih-medium ip-gray radius-xs b-light"
                placeholder="Data de Retorno" data-from-field="txtDateFrom" data-to-field="txtDateTo"
                autocomplete="off" />
        </div>
    </div>
    <div class="col-md-2">
        <div class="dm-select">
            <select class="form-control form-control-lg ps-3 pe-5" name="shipp_f">
                <option value="" selected>Todos Fretes</option>
                {% for shipp_s in shipp_list %}
                    <option value="{{ shipp_s.0 }}">{{ shipp_s.1 }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md-2">
        <div class="dm-select">
            <select class="form-control form-control-lg ps-3 pe-5" name="oper_f">
                <option value="" selected>Todas Operadoras</option>
                {% for op_s in oper_list %}
                <option value="{{op_s.0}}">{{op_s.1}}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="col-md-1">
        <button type="submit" class="btn btn-default btn-rounded color-primary btn-primary"
            name="up_filter">Filtrar</button>
    </div>
    <div class="col-md-1 p-2">
        <div class="application-task d-flex align-items-center">
            <a class="btn-default btn-rounded" href="{% url 'sims_add_sim' %}">
                <i class="bi bi-arrow-clockwise"></i>Limpar
            </a>
        </div>
    </div>
</form>
</div>

<form class="row g-3" action="{% url 'sims_add_sim' %}" method="POST">
{% csrf_token %}
<div class="table-responsive">
        <table class="table mb-0 table-hover table-responsive">
            <thead>
                <tr class="userDatatable-header">
                    <th class="userDatatable-title text-left"><input class="form-check-input" type="checkbox" id="checkAll"></th>
                    <th class="userDatatable-title text-left">Pedido</th>
                    <th class="userDatatable-title text-left">Data</th>
                    <th class="userDatatable-title text-left">Cliente</th>
                    <th class="userDatatable-title text-left">Plano</th>
                    <th class="userDatatable-title text-left">Operadora</th>
                    <th class="userDatatable-title text-left">SIM</th>
                    <th class="userDatatable-title text-left">Frete</th>
                </tr>
            </thead>
            <tbody>
                {% if orders %}
                {% for order in orders %}
                <tr class="table-tr">
                    <td class="text-left">
                        <div class="userDatatable-content">
                            <input type="hidden" name="ord_id" value="{{ order.id }}">
                            {% for oper in oper_list %}
                                {% if oper.0 == order.oper_sim %}
                                    <input type="hidden" name="ord_oper_{{ order.id }}" value="{{ oper.0 }}">
                                {% endif %}
                            {% endfor %}
                        </div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">{{ order.item_id }}</div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">{{ order.order_date|date:'d/m/Y h:m' }}h</div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">{{ order.client|truncatechars:25 }}</div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">{{ order.get_product_display }}</div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">
                            {% for oper in oper_list %}
                                {% if oper.0 == order.oper_sim %}
                                    {{ oper.1 }}
                                {% endif %}
                            {% endfor %}
                        </div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">
                            <input type="text" class="form-control small" name="ord_sim_{{ order.id }}" value="">
                        </div>
                    </td>
                    <td class="text-left">
                        <div class="userDatatable-content">
                            {{ order.shipping }}
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% else %}
                <tr class="table-tr">
                    <td>
                        <div class="userDatatable-content">
                            Nenhum pedido encontrado.
                        </div>
                    </td>
                </tr>
                {% endif %}
            </tbody>
        </table>
        <button type="submit" class="btn btn-default btn-rounded color-primary btn-primary mt-5"
            name="save_sims">Salvar SIMs</button>
</div>
</form>

{% endblock %}
{% block script_custom %}
<script>
    $(document).ready(function () {
        // Ação do botão "Marcar Todos"
        $('#checkAll').on('change', function () {
            $('.checkItem').prop('checked', this.checked);
        });
    });
</script>
<script>
    /* Tooltips */
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    /* Popovers */
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
</script>
{% endblock %}

templates/painel/sims/index.html
{% extends 'painel/partials/_content_default.html' %}
{% load permission_tags %}
{% load static %}
{% load date_day %}
{% block title_page %}<i class="bi bi-sim"></i> SIMs{% endblock %}
{% block title_content %}Estoque SIMs{% endblock %}
{%block js_custom %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
{% endblock %}

{% block content_top %}
<!-- Conteúdo do topo -->
<!-- {% include 'painel/partials/_sims_stock.html' %} -->
{% endblock %}

{% block content_def %}
<!-- Conteúdo do Principal -->
<div class="row">
    <form class="row g-3" action="" method="POST">
        {% csrf_token %}
        <div class="col-md-1">
            <div class="dm-select">
                <select class="form-control form-control-lg ps-3 pe-5" name="sim_st">
                    <option value="" selected>Alterar Status</option>
                    {% for sim_st in sims_status %}
                    <option value="{{sim_st.0}}">{{sim_st.1}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="col-md-1">
            <button type="submit" class="btn btn-default btn-rounded color-primary btn-primary"
                name="up_status">Alterar</button>
        </div>
        <div class="col-md-2">
            <input type="text" class="form-control form-control-lg" placeholder="(e)SIM)" name="sim_f">
        </div>
        <div class="col-md-2">
            <div class="dm-select">
                <select class="form-control form-control-lg ps-3 pe-5" name="sim_type_f">
                    <option value="" selected>Filtrar Tipo - Todos</option>
                    {% for sim_t in sims_types %}
                    <option value="{{sim_t.0}}">{{sim_t.1}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <div class="dm-select">
                <select class="form-control form-control-lg ps-3 pe-5" name="sim_status_f">
                    <option value="" selected>Filtrar Status - Todos</option>
                    {% for sim_s in sims_status %}
                    <option value="{{sim_s.0}}">{{sim_s.1}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="col-md-2">
            <div class="dm-select">
                <select class="form-control form-control-lg ps-3 pe-5" name="sim_oper_f">
                    <option value="" selected>Filtrar Operadora - Todos</option>
                    {% for sim_o in sims_oper %}
                    <option value="{{sim_o.0}}">{{sim_o.1}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="col-md-1">
            <button type="submit" class="btn btn-default btn-rounded color-primary btn-primary"
                name="up_filter">Filtrar</button>
        </div>
        <div class="col-md-1 p-2">
            <a class="btn-default btn-rounded" href="{% url 'sims_index' %}">
                <i class="bi bi-arrow-clockwise"></i>Limpar
            </a>
        </div>
        <div class="table-responsive">
            <table class="table mb-0 table-hover table-responsive">
                <thead>
                    <tr class="userDatatable-header">
                        <th><input class="form-check-input" type="checkbox" id="checkAll"></th>
                        <th class="userDatatable-title">SIM</th>
                        <th class="userDatatable-title">Link</th>
                        <th class="userDatatable-title">Tipo Sim</th>
                        <th class="userDatatable-title">Operadora</th>
                        <th class="userDatatable-title">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% if sims %}
                    {% for sim in sims %}
                    <tr class="table-tr">
                        <td>
                            <div class="userDatatable-content">
                                <input class="checkItem form-check-input" type="checkbox" value="{{sim.id}}"
                                    name="sim_id">
                            </div>
                        </td>
                        <td>
                            <div class="userDatatable-content">
                                {{ sim.sim }}
                            </div>
                        </td>
                        <td>
                            <div class="userDatatable-content">
                                {% if sim.type_sim == 'esim' %}
                                <a href="{{ url_cdn }}{{ sim.link }}" target="_blank">{{ sim.sim }}
                                    {% else %}-{% endif %}
                                </a>
                            </div>
                        </td>
                        <td>
                            <div class="userDatatable-content">
                                {{ sim.type_sim }}
                            </div>
                        </td>
                        <td>
                            <div class="userDatatable-content">
                                {{ sim.get_operator_display }}
                            </div>
                        </td>
                        <td>
                            <div class="userDatatable-content">
                                {{ sim.get_sim_status_display }}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td>
                            <div class="userDatatable-content">
                                Nenhum (e)SIM encontrado.
                            </div>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
            <nav aria-label="navigation">
                <ul class="pagination">
                    {% if sims.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ sims.previous_page_number }}{{ url_filter }}"
                            aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    {% endif %}
                    <li class="page-item">
                        <a class="page-link" href="">{{ sims.number }} de {{ sims.paginator.num_pages }}</a>
                    </li>
                    {% if sims.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ sims.next_page_number }}{{ url_filter }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </form>
</div>


{% endblock %}
{% block script_custom %}
<script>
    $(document).ready(function () {
        // Ação do botão "Marcar Todos"
        $('#checkAll').on('change', function () {
            $('.checkItem').prop('checked', this.checked);
        });
    });
</script>
{% endblock %}